from abc import ABC, abstractmethod
from typing import Dict, Optional
import pandas as pd

class Signal:
    """Trading signal generated by a strategy."""
    
    def __init__(self, symbol: str, action: str, confidence: float, reason: str = ""):
        self.symbol = symbol
        self.action = action  # "BUY", "SELL", or "HOLD"
        self.confidence = confidence  # 0.0 to 1.0
        self.reason = reason
    
    def to_dict(self) -> Dict:
        return {
            "symbol": self.symbol,
            "action": self.action,
            "confidence": self.confidence,
            "reason": self.reason
        }

class Strategy(ABC):
    """Base class for all trading strategies."""
    
    def __init__(self, name: str, params: Dict = None):
        self.name = name
        self.params = params or {}
    
    @abstractmethod
    def analyze(self, data: pd.DataFrame, current_symbol: str) -> Signal:
        """
        Analyze market data and generate a trading signal. (Bar-by-bar)
        """
        pass

    def generate_signals(self, data: pd.DataFrame, symbol: str) -> pd.DataFrame:
        """
        Vectorized high-performance signal generation.
        Returns a DataFrame with columns: ['signal', 'confidence', 'reason']
        aligned with the input data index.
        """
        # Default fallback: Iterate (slow, but compatible)
        signals = []
        confidences = []
        reasons = []
        
        for i in range(len(data)):
            current_slice = data.iloc[:i+1]
            try:
                sig = self.analyze(current_slice, symbol)
                signals.append(sig.action)
                confidences.append(sig.confidence)
                reasons.append(sig.reason)
            except:
                signals.append("HOLD")
                confidences.append(0.0)
                reasons.append("")
                
        return pd.DataFrame({
            "signal": signals,
            "confidence": confidences,
            "reason": reasons
        }, index=data.index)
    
    def __str__(self):
        return f"{self.name}({self.params})"
